# Generated by Django 5.2 on 2025-04-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesmodel',
            options={'ordering': ['name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
