version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.3
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tashkent
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6378:6379"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      TZ: Asia/Tashkent

  daphne:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "7009:7009"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
