# Generated by Django 5.2 on 2025-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('dispatcher', 'Dispatcher'), ('carrier', 'Carrier'), ('cargo owner', 'Cargo owner'), ('forwarder', 'Forwarder')], null=True),
        ),
    ]
