# Generated by Django 5.2 on 2025-04-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_given',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_issue_license',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='drivers_license_file',
            field=models.FileField(blank=True, null=True, upload_to='users/drivers_license/'),
        ),
        migrations.AddField(
            model_name='user',
            name='drivers_license_serial_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='given_by_whom',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to='users/passport/'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_serial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
