# Generated by Django 5.2 on 2025-04-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_agree_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='+998 1234567', max_length=20, null=True, unique=True),
        ),
    ]
