# Generated by Django 5.2 on 2025-04-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_date_given_user_date_of_issue_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, help_text='1234567890', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_serial',
            field=models.CharField(blank=True, help_text='AB', max_length=10, null=True),
        ),
    ]
