# Generated by Django 5.2 on 2025-04-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryForDrivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('loading', models.CharField(blank=True, choices=[('from above', 'From above'), ('from the side', 'From the side'), ('from behind', 'From behind'), ('with full awning', 'With full awning'), ('with the removal of crossbars', 'With the removal of crossbars'), ('electricity', 'Electricity')], max_length=255, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=55, null=True, verbose_name='Vehicle')),
                ('body_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume (m³)')),
                ('company', models.CharField(blank=True, max_length=55, null=True, verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='AddCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='m3', max_digits=12, null=True)),
                ('when', models.CharField(blank=True, choices=[('ready_to_download', 'Ready to download'), ('permanent', 'Permanent'), ('no_load', 'No load')], max_length=30)),
                ('GPS_monitoring', models.BooleanField(default=False)),
                ('bid_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('GBP', 'GBP'), ('CNY', 'CNY'), ('KZT', 'KZT'), ('SUM', 'UZS')], default='SUM', max_length=10)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_base.cargotype')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargo',
            },
        ),
    ]
