# Generated by Django 5.2 on 2025-04-28 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo_base', '0001_initial'),
        ('country', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=12, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='m', max_digits=12, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='m', max_digits=12, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='m', max_digits=12, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='m3', max_digits=12, null=True)),
                ('when', models.CharField(blank=True, choices=[('ready_to_download', 'Ready to download'), ('permanent', 'Permanent'), ('no_load', 'No load')], max_length=30)),
                ('GPS_monitoring', models.BooleanField(default=False)),
                ('bid_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('GBP', 'GBP'), ('CNY', 'CNY'), ('KZT', 'KZT'), ('SUM', 'UZS')], default='SUM', max_length=10)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_in_UZS', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cargo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_base.cargotype')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_roles', to=settings.AUTH_USER_MODEL)),
                ('loading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loading', to='country.district')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicesmodel')),
                ('unloading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unloading', to='country.district')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='DeliveryForDrivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('car_model', models.CharField(blank=True, choices=[('truck', 'Truck'), ('semitrailer', 'Semitrailer')], max_length=255, null=True)),
                ('loading', models.CharField(blank=True, choices=[('top', 'Top'), ('lateral', 'Lateral'), ('back', 'Back'), ('with full awning', 'With full awning'), ('with the removal of crossbars', 'With the removal of crossbars')], max_length=255, null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='kg', max_digits=12)),
                ('length', models.DecimalField(decimal_places=2, help_text='m', max_digits=12)),
                ('width', models.DecimalField(decimal_places=2, help_text='m', max_digits=12)),
                ('height', models.DecimalField(decimal_places=2, help_text='m', max_digits=12)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='m3', max_digits=12, null=True)),
                ('GPS_monitoring', models.BooleanField(default=False)),
                ('when', models.CharField(blank=True, choices=[('ready_to_download', 'Ready to download'), ('permanent', 'Permanent'), ('no_load', 'No load')], max_length=30)),
                ('bid_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('GBP', 'GBP'), ('CNY', 'CNY'), ('KZT', 'KZT'), ('SUM', 'UZS')], default='SUM', max_length=10)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_in_UZS', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_where', to='country.district')),
                ('where_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_where_to', to='country.district')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
    ]
