# Generated by Django 5.2 on 2025-04-22 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo_base', '0001_initial'),
        ('country', '0001_initial'),
        ('order', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfordrivers',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryfordrivers',
            name='where',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.district'),
        ),
        migrations.AddField(
            model_name='deliveryfordrivers',
            name='where_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_where_to', to='country.district'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_base.cargoelements'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='download',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryrequest_download', to='country.district'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='loading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryrequest_loading', to='country.district'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesmodel'),
        ),
    ]
