# Generated by Django 5.2 on 2025-04-24 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        ('order', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addcargo',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addcargo',
            name='loading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loading', to='country.district'),
        ),
        migrations.AddField(
            model_name='addcargo',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicesmodel'),
        ),
        migrations.AddField(
            model_name='addcargo',
            name='unloading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unloading', to='country.district'),
        ),
        migrations.AddField(
            model_name='deliveryfordrivers',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryfordrivers',
            name='where',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.district'),
        ),
        migrations.AddField(
            model_name='deliveryfordrivers',
            name='where_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_where_to', to='country.district'),
        ),
    ]
