# Generated by Django 5.2 on 2025-04-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcargo',
            name='currency_exchange_to_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='addcargo',
            name='uzs_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='addcargo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=12, null=True),
        ),
    ]
