# Generated by Django 5.2 on 2025-04-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryfordrivers',
            name='body_volume',
        ),
        migrations.RemoveField(
            model_name='deliveryfordrivers',
            name='company',
        ),
        migrations.RemoveField(
            model_name='deliveryfordrivers',
            name='vehicle',
        ),
    ]
