# Generated by Django 5.2 on 2025-04-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcargo',
            old_name='cargo',
            new_name='cargo_type',
        ),
    ]
