# Generated by Django 5.2 on 2025-04-25 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_district_options_alter_district_name_and_more'),
        ('order', '0003_rename_cargo_addcargo_cargo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcargo',
            name='loading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loading', to='country.district'),
        ),
    ]
