# Generated by Django 5.2 on 2025-04-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_addcargo_currency_exchange_to_sum_addcargo_uzs_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcargo',
            name='uzs_price',
        ),
    ]
