# Generated by Django 5.2 on 2025-04-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_deliveryfordrivers_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcargo',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=1, help_text='m3', max_digits=12),
            preserve_default=False,
        ),
    ]
