# Generated by Django 5.2 on 2025-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_addcargo_uzs_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcargo',
            old_name='currency_exchange_to_sum',
            new_name='price_in_UZS',
        ),
        migrations.AlterField(
            model_name='addcargo',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
