# Generated by Django 5.2 on 2025-04-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_base', '0001_initial'),
        ('order', '0005_rename_currency_exchange_to_sum_addcargo_price_in_uzs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcargo',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='addcargo',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='addcargo',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliveryfordrivers',
            name='load_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliveryfordrivers',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m3', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='addcargo',
            name='bid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='addcargo',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_base.cargotype'),
        ),
        migrations.AlterField(
            model_name='deliveryfordrivers',
            name='loading',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('lateral', 'Lateral'), ('back', 'Back'), ('with full awning', 'With full awning'), ('with the removal of crossbars', 'With the removal of crossbars')], max_length=255, null=True),
        ),
    ]
