# Generated by Django 5.2 on 2025-04-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_addcargo_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcargo',
            name='when_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
