# Generated by Django 5.2 on 2025-04-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_deliveryfordrivers_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcargo',
            name='when_to',
            field=models.CharField(blank=True, choices=[('every_day', 'Every day'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=30, null=True),
        ),
    ]
