# Generated by Django 5.2 on 2025-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_addcargo_when_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcargo',
            name='loading_body',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('lateral', 'Lateral'), ('back', 'Back'), ('with full awning', 'With full awning'), ('with the removal of crossbars', 'With the removal of crossbars')], max_length=50, null=True),
        ),
    ]
