# Generated by Django 5.2 on 2025-04-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_district_options_alter_district_name_and_more'),
        ('order', '0006_addcargo_when_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcargo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='addcargo',
            name='when_to',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryfordrivers',
            name='where',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_where', to='country.district'),
        ),
    ]
