# Generated by Django 5.2 on 2025-04-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_addcargo_weight_alter_addcargo_when_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcargo',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='addcargo',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='addcargo',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m', max_digits=12, null=True),
        ),
    ]
