# Generated by Django 5.2 on 2025-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_addcargo_loading_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryfordrivers',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m3', max_digits=12, null=True),
        ),
    ]
