# Generated by Django 5.2 on 2025-04-29 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_deliveryfordrivers_volume'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfordrivers',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_services', to='services.servicesmodel'),
        ),
    ]
