# Generated by Django 5.2 on 2025-04-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_addcargo_height_alter_addcargo_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcargo',
            name='bid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
