# Generated by Django 5.2 on 2025-04-28 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_addcargo_bid_price'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcargo',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicesmodel'),
        ),
    ]
