# Generated by Django 5.2 on 2025-04-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_region_lat_region_lon_region_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('-created_at',), 'verbose_name': 'Tuman', 'verbose_name_plural': 'Tumanlar'},
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
    ]
